#!/usr/bin/env python3
"""Generate an index.html for GitHub Pages listing all frontend runs."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "frontend"

TIER_ORDER = ["T1", "T2", "T3", "T4", "T5", "T6", "C1", "C2", "LX"]


def scan_runs():
    """Scan all frontend run folders and return structured data."""
    runs = []
    for task_dir in sorted(FRONTEND.iterdir()):
        if not task_dir.is_dir():
            continue
        name = task_dir.name
        # Parse tier and level from folder name
        if name.startswith("frontend_"):
            parts = name.replace("frontend_", "", 1)
            if "_" in parts:
                tier, level = parts.split("_", 1)
            else:
                tier, level = parts, ""
        elif name.startswith("lx_"):
            tier, level = "LX", name.replace("lx_", "", 1)
        else:
            continue

        for uuid_dir in sorted(task_dir.iterdir()):
            if not uuid_dir.is_dir():
                continue
            main_dir = uuid_dir / "main"
            if main_dir.is_dir() and (main_dir / "index.html").exists():
                runs.append({
                    "task": name,
                    "tier": tier,
                    "level": level,
                    "uuid": uuid_dir.name,
                    "path": f"frontend/{name}/{uuid_dir.name}/main/",
                })
    return runs


def generate_html(runs):
    """Generate the HTML index page."""
    # Group by tier
    grouped = {}
    for run in runs:
        grouped.setdefault(run["tier"], []).append(run)

    rows = ""
    for tier in TIER_ORDER:
        tier_runs = grouped.get(tier, [])
        if not tier_runs:
            continue
        rows += f'    <tr class="tier-header"><td colspan="4">{tier}</td></tr>\n'
        for r in tier_runs:
            rows += (
                f'    <tr>\n'
                f'      <td>{r["tier"]}</td>\n'
                f'      <td>{r["level"]}</td>\n'
                f'      <td><code>{r["uuid"][:8]}...</code></td>\n'
                f'      <td><a href="{r["path"]}" target="_blank">Open</a></td>\n'
                f'    </tr>\n'
            )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Orcheeos Agent Workspace</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #0d1117; color: #c9d1d9; padding: 2rem; }}
  h1 {{ color: #58a6ff; margin-bottom: 0.5rem; font-size: 1.8rem; }}
  p.sub {{ color: #8b949e; margin-bottom: 2rem; }}
  table {{ width: 100%; border-collapse: collapse; max-width: 900px; }}
  th, td {{ text-align: left; padding: 0.6rem 1rem; border-bottom: 1px solid #21262d; }}
  th {{ background: #161b22; color: #58a6ff; position: sticky; top: 0; }}
  tr:hover {{ background: #161b22; }}
  .tier-header td {{ background: #1c2333; color: #58a6ff; font-weight: bold;
                     font-size: 1.1rem; padding-top: 1rem; }}
  a {{ color: #58a6ff; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  code {{ background: #161b22; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.85rem; }}
  .stats {{ color: #8b949e; margin-bottom: 1.5rem; }}
</style>
</head>
<body>
<h1>Orcheeos Agent Workspace</h1>
<p class="sub">Live previews of frontend outputs generated by multi-agent architectures.</p>
<p class="stats">{len(runs)} runs across {len(grouped)} tiers</p>
<table>
  <thead>
    <tr><th>Tier</th><th>Level</th><th>UUID</th><th>Preview</th></tr>
  </thead>
  <tbody>
{rows}  </tbody>
</table>
</body>
</html>"""
    return html


if __name__ == "__main__":
    runs = scan_runs()
    html = generate_html(runs)
    out = ROOT / "index.html"
    out.write_text(html)
    print(f"Generated {out} with {len(runs)} runs")
